name: pockert-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "4983:4983"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit